version: "3.7"

services:
    # image project
    app:
        container_name: desafio-app
        build:
            context: .
            dockerfile: Dockerfile
        image: desafio
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - desafio

    # nginx
    nginx:
        container_name: desafio-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - desafio

    # db mysql
    mysql:
        container_name: desafio-mysql
        image: mysql:5.7.39
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - "3388:3306"

        networks:
            - desafio

networks:
    desafio:
        driver: bridge

